version: 2

models:
  - name: dim_state
    description: "State dimension table with surrogate key"
    columns:
      - name: id
        tests:
          - unique
          - not_null          
      - name: code
        description: "Two-letter state code (natural key)"
        tests:
          - unique
          - not_null          
      - name: name
        description: "Full state name"
        tests:
          - unique
          - not_null          
      - name: updated_at
        tests:
          - not_null

  - name: dim_ammendment_code
    description: "Indicates if the report being filed is new (N), an amendment (A) to a previous report or a termination (T) report"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null     

  - name: dim_candidate_status
    description: "C=Statutory candidate, F=Statutory candidate for future election, N=Not yet a statutory candidate, P=Statutory candidate in prior cycle"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null   

  - name: dim_committee_designation
    description: "A=Authorized by a candidate, B=Lobbyist/Registrant PAC, D=Leadership PAC, J=Joint fundraiser, P=Principal campaign committee of a candidate, U=Unauthorized"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null                               

  - name: dim_committee_type
    description: "Many - presidential, senate, PAC, etc."
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: explanation    
      - name: updated_at
        tests:
          - not_null 

  - name: dim_entity_type
    description: "ONLY VALID FOR ELECTRONIC FILINGS received after April 2002"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null       

  - name: dim_incumbent_challenger_status
    description: "C=Challenger, I=Incumbent, O=Open Seat is used to indicate an open seat; Open seats are defined as seats where the incumbent never sought re-election."
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null 

  - name: dim_office
    description: "H=House, P=President, S=Senate"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null            

  - name: dim_party
    description: "The political party affiliation reported by the candidate."
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null   

  - name: dim_primary_general_indicator
    description: "P=Primary, G=General, O=Other, C=Convention, R=Runoff, S=Special, E=Recount"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null    

  - name: dim_report_type
    description: "Indicates the type of report filed."
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null    
      - name: updated_at
        tests:
          - not_null             

  - name: dim_transaction_type
    description: "Transaction types 24A, 24C, 24E, 24F, 24H, 24K, 24N, 24P, 24R, 24Z are included in the PAS2 file"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: description
        tests:
          - unique
          - not_null   
      - name: updated_at
        tests:
          - not_null            

  - name: dim_candidate
    description: "Dimensional model of FEC candidates with integer foreign keys to reference tables"
    tests:
      - rowcount_match_with_default:
          compare_to: "{{ source('raw', 'candidate') }}"
    columns:
      - name: id
        tests:
          - unique
          - not_null
          
      - name: cand_id
        description: "FEC candidate identification number"
        tests:
          - unique
          - not_null
          
      - name: cand_name
        description: "Candidate name"
        tests:
          - not_null
      
      # Foreign Keys
      - name: party_id
        description: "Foreign key to dim_party table"
        tests:
          - relationships:
              to: ref('dim_party')
              field: id
          - not_null 

      - name: office_id
        description: "Foreign key to dim_office table"
        tests:
          - relationships:
              to: ref('dim_office')
              field: id
          - not_null     

      - name: office_state_id
        description: "Foreign key to dim_state table for office state"
        tests:
          - relationships:
              to: ref('dim_state')
              field: id
          - not_null 

      - name: candidate_status_id
        description: "Foreign key to dim_candidate_status"
        tests:
          - relationships:
              to: ref('dim_candidate_status')
              field: id
          - not_null 
          
      - name: incumbent_challenger_status_id
        description: "Foreign key to dim_incumbent_challenger_status"
        tests:
          - relationships:
              to: ref('dim_incumbent_challenger_status')
              field: id
          - not_null 

      - name: mailing_state_id
        description: "Foreign key to dim_states"
        tests:
          - relationships:
              to: ref('dim_state')
              field: id
          - not_null 
          
      # Descriptive Attributes  
      - name: election_year
        description: "Year of election"
        
      - name: office_district
        description: "Congressional district number"
        
      - name: principal_campaign_committee
        description: "Principal campaign committee ID"
        
      - name: street_1
        description: "Mailing address street 1"
        
      - name: street_2
        description: "Mailing address street 2"
        
      - name: city
        description: "Mailing address city"
        
      - name: zip_code
        description: "Mailing address ZIP code"    

      - name: source_file_year
        description: "Year from the FEC file"
        tests:
          - not_null        

  - name: dim_committee
    description: "Dimensional model of FEC committees with integer foreign keys to reference tables"
    tests:
      - rowcount_match_with_default:
          compare_to: "{{ source('raw', 'committee') }}"
    columns:
      - name: id
        description: "Auto-incrementing surrogate primary key"
        tests:
          - unique
          - not_null
          
      - name: cmte_id
        description: "FEC committee identification number"
        tests:
          # NOT Unique, because the same ID can appear for each election cycle
          - not_null
          
      - name: committee_name
        description: "Committee name"
        tests:
          - not_null
          
      - name: treasurer_name
        description: "Treasurer name"
      
      # Foreign Keys
      - name: state_id
        description: "Foreign key to dim_state table"
        tests:
          - relationships:
              to: ref('dim_state')
              field: id
          - not_null

      - name: committee_designation_id
        description: "Foreign key to dim_committee_designation table"
        tests:
          - relationships:
              to: ref('dim_committee_designation')
              field: id
          - not_null

      - name: committee_type_id
        description: "Foreign key to dim_committee_type table"
        tests:
          - relationships:
              to: ref('dim_committee_type')
              field: id
          - not_null

      - name: party_id
        description: "Foreign key to dim_party table"
        tests:
          - relationships:
              to: ref('dim_party')
              field: id
          - not_null

      - name: entity_type_id
        description: "Foreign key to dim_entity_type table"
        tests:
          - relationships:
              to: ref('dim_entity_type')
              field: id
          - not_null

      - name: filing_frequency_id
        description: "Foreign key to dim_committee_filing_frequency table"
        tests:
          - relationships:
              to: ref('dim_committee_filing_frequency')
              field: id
          - not_null

      - name: interest_group_category_id
        description: "Foreign key to dim_interest_group_category table"
        tests:
          - relationships:
              to: ref('dim_interest_group_category')
              field: id
          - not_null

      - name: candidate_id
        description: "Foreign key to dim_candidate table (nullable for committees not linked to candidates)"
        tests:
          - relationships:
              to: ref('dim_candidate')
              field: id

      # Descriptive Attributes  
      - name: street_1
        description: "Mailing address street 1"
        
      - name: street_2
        description: "Mailing address street 2"
        
      - name: city
        description: "Mailing address city"
        
      - name: zip_code
        description: "Mailing address ZIP code"
        
      - name: connected_organization_name
        description: "Name of connected organization"

      - name: source_file_year
        description: "Year from the FEC file"
        tests:
          - not_null

  - name: fact_committee_contribution
    description: "Committee contributions to candidates"
    tests:
      # Confirm we got all the rows from the source table
      - rowcount_match:
          compare_to: "{{ source('raw', 'committee_contricflearbution') }}"
    columns:
      - name: id
        description: "Auto-incrementing surrogate primary key"
        tests:
          - unique
          - not_null
          
      - name: sub_id
        description: "FEC submission ID (unique transaction identifier)"
        tests:
          - unique
          - not_null
          
      - name: transaction_id
        description: "Transaction ID"
        
      - name: file_number
        description: "File number"
        
      - name: image_number
        description: "Image number"
      
      # Foreign Keys
      - name: committee_id
        description: "Foreign key to dim_committee table"
        tests:
          - relationships:
              to: ref('dim_committee')
              field: id
          - not_null

      - name: candidate_id
        description: "Foreign key to dim_candidate table (nullable)"
        tests:
          - relationships:
              to: ref('dim_candidate')
              field: id

      - name: state_id
        description: "Foreign key to dim_state table for contributor state"
        tests:
          - relationships:
              to: ref('dim_state')
              field: id
          - not_null

      - name: amendment_indicator_id
        description: "Foreign key to dim_ammendment_code table"
        tests:
          - relationships:
              to: ref('dim_ammendment_code')
              field: id
          - not_null

      - name: report_type_id
        description: "Foreign key to dim_report_type table"
        tests:
          - relationships:
              to: ref('dim_report_type')
              field: id
          - not_null

      - name: primary_general_indicator_id
        description: "Foreign key to dim_primary_general_indicator table"
        tests:
          - relationships:
              to: ref('dim_primary_general_indicator')
              field: id
          - not_null

      - name: transaction_type_id
        description: "Foreign key to dim_transaction_type table"
        tests:
          - relationships:
              to: ref('dim_transaction_type')
              field: id
          - not_null

      - name: entity_type_id
        description: "Foreign key to dim_entity_type table"
        tests:
          - relationships:
              to: ref('dim_entity_type')
              field: id
          - not_null

      - name: transaction_date
        description: "Date of the transaction"
        # For 2025-2026 15 of these were null - need to fix somehow..
        # tests:
        #  - not_null    

      # Measures
      - name: transaction_amount
        description: "Transaction amount in dollars"
        tests:
          - not_null
      
      # Contributor Information
      - name: contributor_name
        description: "Name of the contributor"
        
      - name: contributor_city
        description: "City of the contributor"
        
      - name: contributor_zip_code
        description: "ZIP code of the contributor"
        
      - name: contributor_employer
        description: "Employer of the contributor"
        
      - name: contributor_occupation
        description: "Occupation of the contributor"
      
      # Other Fields
      - name: other_id
        description: "Other ID field"
        
      - name: memo_code
        description: "Memo code"

      - name: memo_text
        description: "Memo text"     

      - name: source_file_year
        description: "Year from the FEC file"
        tests:
          - not_null

  - name: fact_individual_contribution
    description: "Individual contributions to committees"
    tests:
    # Confirm we got all the rows from the source table
    - rowcount_match:
        compare_to: "{{ source('raw', 'individual_contribution') }}"

    columns:
      - name: id
        description: "Auto-incrementing surrogate primary key"
        tests:
          - unique
          - not_null
          
      - name: sub_id
        description: "FEC submission ID (unique transaction identifier)"
        tests:
          - unique
          - not_null
          
      - name: transaction_id
        description: "Transaction ID"
        
      - name: file_number
        description: "File number"
        
      - name: image_number
        description: "Image number"
      
      # Foreign Keys
      - name: committee_id
        description: "Foreign key to dim_committee table"
        tests:
          - relationships:
              to: ref('dim_committee')
              field: id
          - not_null

      - name: state_id
        description: "Foreign key to dim_state table for contributor state"
        tests:
          - relationships:
              to: ref('dim_state')
              field: id
          - not_null

      - name: amendment_indicator_id
        description: "Foreign key to dim_ammendment_code table"
        tests:
          - relationships:
              to: ref('dim_ammendment_code')
              field: id
          - not_null

      - name: report_type_id
        description: "Foreign key to dim_report_type table"
        tests:
          - relationships:
              to: ref('dim_report_type')
              field: id
          - not_null

      - name: primary_general_indicator_id
        description: "Foreign key to dim_primary_general_indicator table"
        tests:
          - relationships:
              to: ref('dim_primary_general_indicator')
              field: id
          - not_null

      - name: transaction_type_id
        description: "Foreign key to dim_transaction_type table"
        tests:
          - relationships:
              to: ref('dim_transaction_type')
              field: id
          - not_null

      - name: entity_type_id
        description: "Foreign key to dim_entity_type table"
        tests:
          - relationships:
              to: ref('dim_entity_type')
              field: id
          - not_null

      # Measures and Facts
      - name: transaction_date
        description: "Date of the transaction"
          
      - name: transaction_amount
        description: "Transaction amount in dollars"
        tests:
          - not_null
      
      # Contributor Information
      - name: contributor_name
        description: "Name of the contributor"
        
      - name: contributor_city
        description: "City of the contributor"
        
      - name: contributor_zip_code
        description: "ZIP code of the contributor"
        
      - name: contributor_employer
        description: "Employer of the contributor"
        
      - name: contributor_occupation
        description: "Occupation of the contributor"
      
      # Other Fields
      - name: other_id
        description: "Other ID field"
        
      - name: memo_code
        description: "Memo code"
        
      - name: memo_text
        description: "Memo text"      

      - name: source_file_year
        description: "Year from the FEC file"
        tests:
          - not_null   


  # Views
  - name: dim_candidate_view
    description: "Candidates joined to all dimensions"
    tests:
      # Confirm the dim_candidate_view has equal # of rows as the base dim_candidate
      - rowcount_match:
          compare_to: ref('dim_candidate')

  - name: dim_committee_view
    description: "Denormalized view of committees with all dimension lookups for easy querying"
    tests:
      - rowcount_match:
          compare_to: ref('dim_committee')    

  - name: committee_contribution_view
    description: "Fully denormalized committee contributions with all dimension lookups"
    tests:
      - rowcount_match:
          compare_to: ref('fact_committee_contribution')            



