version: 2

models:
  - name: dim_state
    description: "State dimension table with surrogate key"
    columns:
      - name: id
        tests:
          - unique
          - not_null          
      - name: code
        description: "Two-letter state code (natural key)"
        tests:
          - unique
          - not_null          
      - name: name
        description: "Full state name"
        tests:
          - unique
          - not_null          
      - name: updated_at
        tests:
          - not_null

  - name: dim_ammendment_code
    description: "Indicates if the report being filed is new (N), an amendment (A) to a previous report or a termination (T) report"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null     

  - name: dim_candidate_status
    description: "C=Statutory candidate, F=Statutory candidate for future election, N=Not yet a statutory candidate, P=Statutory candidate in prior cycle"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null   

  - name: dim_committee_designation
    description: "A=Authorized by a candidate, B=Lobbyist/Registrant PAC, D=Leadership PAC, J=Joint fundraiser, P=Principal campaign committee of a candidate, U=Unauthorized"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null                               

  - name: dim_committee_type
    description: "Many - presidential, senate, PAC, etc."
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: explanation    
      - name: updated_at
        tests:
          - not_null 

  - name: dim_entity_type
    description: "ONLY VALID FOR ELECTRONIC FILINGS received after April 2002"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null       

  - name: dim_incumbent_challenger_status
    description: "C=Challenger, I=Incumbent, O=Open Seat is used to indicate an open seat; Open seats are defined as seats where the incumbent never sought re-election."
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null 

  - name: dim_office
    description: "H=House, P=President, S=Senate"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null            

  - name: dim_party
    description: "The political party affiliation reported by the candidate."
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: notes    
      - name: updated_at
        tests:
          - not_null   

  - name: dim_primary_general_indicator
    description: "P=Primary, G=General, O=Other, C=Convention, R=Runoff, S=Special, E=Recount"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
      - name: updated_at
        tests:
          - not_null    

  - name: dim_report_type
    description: "Indicates the type of report filed."
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null    
      - name: updated_at
        tests:
          - not_null             

  - name: dim_transaction_type
    description: "Transaction types 24A, 24C, 24E, 24F, 24H, 24K, 24N, 24P, 24R, 24Z are included in the PAS2 file"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: code
        tests:
          - unique
          - not_null
      - name: description
        tests:
          - unique
          - not_null   
      - name: updated_at
        tests:
          - not_null            

  - name: dim_candidate
    description: "Dimensional model of FEC candidates with integer foreign keys to reference tables"
    columns:
      - name: id
        tests:
          - unique
          - not_null
          
      - name: cand_id
        description: "FEC candidate identification number"
        tests:
          - unique
          - not_null
          
      - name: cand_name
        description: "Candidate name"
        tests:
          - not_null
      
      # Foreign Keys
      - name: party_id
        description: "Foreign key to dim_party table"
        tests:
          - relationships:
              to: ref('dim_party')
              field: id
          - not_null 

      - name: office_id
        description: "Foreign key to dim_office table"
        tests:
          - relationships:
              to: ref('dim_office')
              field: id
          - not_null     

      - name: office_state_id
        description: "Foreign key to dim_state table for office state"
        tests:
          - relationships:
              to: ref('dim_state')
              field: id
          - not_null 

      - name: candidate_status_id
        description: "Foreign key to dim_candidate_status"
        tests:
          - relationships:
              to: ref('dim_candidate_status')
              field: id
          - not_null 
          
      - name: incumbent_challenger_status_id
        description: "Foreign key to dim_incumbent_challenger_status"
        tests:
          - relationships:
              to: ref('dim_incumbent_challenger_status')
              field: id
          - not_null 

      - name: mailing_state_id
        description: "Foreign key to dim_states"
        tests:
          - relationships:
              to: ref('dim_state')
              field: id
          - not_null 
          
      # Descriptive Attributes  
      - name: election_year
        description: "Year of election"
        
      - name: office_district
        description: "Congressional district number"
        
      - name: principal_campaign_committee
        description: "Principal campaign committee ID"
        
      - name: street_1
        description: "Mailing address street 1"
        
      - name: street_2
        description: "Mailing address street 2"
        
      - name: city
        description: "Mailing address city"
        
      - name: zip_code
        description: "Mailing address ZIP code"          


  # Views
  - name: dim_candidate_view
    description: "Candidates joined to all dimensions"
    tests:
      # Confirm the dim_candidate_view has equal # of rows as the base dim_candidate
      - rowcount_match:
          compare_to: ref('dim_candidate')
