version: 2

sources:
  - name: raw
    database: fec 
    schema: raw
    tables:
      - name: candidate
      - name: candidate_committee
      - name: committee
      - name: committee_contribution
      - name: individual_contribution

  