version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: candidate
      - name: CANDIDATE_COMMITTEE
      - name: COMMITTEE
      - name: COMMITTEE_CONTRIBUTION
      - name: INDIVIDUAL_CONTRIBUTION