--  Run this in snowflake UI first to create the database and schema 
CREATE OR REPLACE DATABASE FEC COMMENT='Data from Fedderal Election Commission website: https://www.fec.gov/data/browse-data/?tab=bulk-data';


USE DATABASE FEC;
GRANT USAGE ON DATABASE FEC TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT CREATE SCHEMA ON DATABASE FEC TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT USAGE ON WAREHOUSE SNOWFLAKE_LEARNING_WH TO ROLE SNOWFLAKE_LEARNING_ROLE;

CREATE SCHEMA RAW;
GRANT ALL ON SCHEMA raw TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT CREATE STAGE ON SCHEMA raw TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA raw TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT CREATE TABLE ON SCHEMA raw TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FEC.RAW TO ROLE SNOWFLAKE_LEARNING_ROLE;

CREATE SCHEMA DIMENSIONAL;
GRANT ALL ON SCHEMA DIMENSIONAL TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT CREATE STAGE ON SCHEMA DIMENSIONAL TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA DIMENSIONAL TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT CREATE TABLE ON SCHEMA DIMENSIONAL TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FEC.DIMENSIONAL TO ROLE SNOWFLAKE_LEARNING_ROLE;

CREATE SCHEMA ANALYTICS;
GRANT ALL ON SCHEMA ANALYTICS TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT CREATE STAGE ON SCHEMA ANALYTICS TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA ANALYTICS TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT CREATE TABLE ON SCHEMA ANALYTICS TO ROLE SNOWFLAKE_LEARNING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FEC.ANALYTICS TO ROLE SNOWFLAKE_LEARNING_ROLE;



-- Run this and paste results into .env (edit your password)
SELECT
    'SNOWFLAKE_USER=' || CURRENT_USER() AS env_var
UNION ALL
SELECT
    'SNOWFLAKE_ACCOUNT=' || CURRENT_ACCOUNT()
UNION ALL
SELECT
    'SNOWFLAKE_ROLE=' || CURRENT_ROLE()
UNION ALL
SELECT
    'SNOWFLAKE_WAREHOUSE=' || CURRENT_WAREHOUSE()
UNION ALL
SELECT
    'SNOWFLAKE_DATABASE=' || CURRENT_DATABASE()
UNION ALL
SELECT
    'SNOWFLAKE_SCHEMA=' || CURRENT_SCHEMA()
UNION ALL
SELECT
    'SNOWFLAKE_PASSWORD=PUT_PASSWORD_HERE!!';




    