version: 2

seeds:
  - name: state
    description: "US state reference data"
    columns:
      - name: code
        description: "Two-letter state code"
        tests:
          - unique
          - not_null
      - name: name    
        description: "State name"
        tests:
          - unique
          - not_null

  - name: ammendment_code
    description: "Indicates if the report being filed is new (N), an amendment (A) to a previous report or a termination (T) report"
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name    
        tests:
          - unique
          - not_null

  - name: candidate_status
    description: "C = Statutory candidate, F = Statutory candidate for future election, N = Not yet a statutory candidate, P = Statutory candidate in prior cycle"
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name    
        tests:
          - unique
          - not_null     

  - name: committee_designation
    description: "A = Authorized by a candidate, B = Lobbyist/Registrant PAC, D = Leadership PAC, J = Joint fundraiser, P = Principal campaign committee of a candidate, U = Unauthorized"
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name    
        tests:
          - unique
          - not_null            

  - name: committee_type
    description: "Many - presidential, senate, PAC, etc."
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name    
        tests:
          - unique
          - not_null 
      - name: explanation 

  - name: entity_type
    description: "ONLY VALID FOR ELECTRONIC FILINGS received after April 2002."
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name    
        tests:
          - unique
          - not_null

  - name: incumbent_challenger_status
    description: "C = Challenger, I = Incumbent,O = Open Seat is used to indicate an open seat; Open seats are defined as seats where the incumbent never sought re-election."
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name    
        tests:
          - unique
          - not_null

  - name: office
    description: "H = House, P = President, S = Senate"
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name    
        tests:
          - unique
          - not_null  

  - name: party
    description: "The political party affiliation reported by the candidate."
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name    
        tests:
          - unique
          - not_null 
      - name: notes           

  - name: primary_general_indicator
    description: "P = Primary, G = General, O = Other, C = Convention, R = Runoff, S = Special, E = Recount"
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name    
        tests:
          - unique
          - not_null      

  - name: transaction_type
    description: "Transaction types 24A, 24C, 24E, 24F, 24H, 24K, 24N, 24P, 24R, 24Z are included in the PAS2 file"
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: description   
        tests:
          - unique
          - not_null  
