
name: 'transform'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'transform'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  transform:
    +schema: raw
    +persist_docs:     # Stores any descriptions in schema.yml as table comments  
      relation: true
      columns: true

# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  transform:
    +persist_docs:   # Stores any descriptions in schema.yml as table comments
      relation: true
      columns: true
    staging:
      +schema: staging   
    dimensional:
      +schema: dimensional
    analytics:
      +schema: analytics